export const emptyStudent = () => ({
  student: {
    orphan: false,
    orphanOf: "",
    orphanDocType: "",
    orphanDocDescription: "",
    registrationPath: "خاص",
    previousClass: "",
    newClass: "",
    status: "resident",
    fullName: "",
    birthdate: "",
    birthPlace: "",
    currentAddress: "",
    gender: "male",
    languages: [],
    hobbies: [],
    addressCodes: {
      sector: "",
      block: "",
      minutes: "",
      floor: "",
      apartment: "",
    },
    chronicDisease: false,
    chronicDiseaseDetails: "",
    permanentHabits: false,
    permanentHabitsDetails: "",
  },
  siblings: [],
  father: {
    name: "",
    alive: true,
    phone: "",
    address: "",
    profession: "",
    whatsapp: "",
    telegram: "",
  },
  mother: {
    name: "",
    alive: true,
    phone: "",
    address: "",
    profession: "",
    whatsapp: "",
    telegram: "",
  },
  general: {
    whatsappGroupPhone: "",
    emergencyContact: { name: "", relation: "", phone: "" },
  },
  previousEducation: [],
  islamicLegalEducation: "",
  bestAchievement: "",
  otherInfo: { familySmokers: false, transportation: "", notes: "" },
  signing: { parentName: "", relationToStudent: "" },
  fees: { academicYear: "", totalPayable: 0 },
  initialPayment: { amount: 0, semester: "full_year", paymentDate: "" },
  currentClassId: "",
  fullInfo: {
    serial: "",
    classSerial: "",
    classSection: "",
    serial2: "",
    department: "",
    generalRegNumber: "",
    ministerialNumber: "",
    fatherFirstName: "",
    familyName: "",
    secondName: "",
    tripleName: "",
    motherTripleName: "",
    grandfatherName: "",
    ageYears: "",
    nationality: "",
    familyStatus: "",
    primaryLanguage: "",
    distinctiveMarks: "",
    bloodType: "",
    familySize: "",
    siblingsInSchool: "",
    livesWith: "",
    housingGovernorate: "",
    housingRegion: "",
    housingDistrict: "",
    housingTown: "",
    recordNumber: "",
    housingType: "",
    housingOwnership: "",
    fatherMaritalStatus: "",
    fatherSpecialty: "",
    motherMaritalStatus: "",
    motherSpecialty: "",
    originalGovernorate: "",
    registrationAmana: "",
    registrationPlace: "",
    registrationNumber: "",
    enrollmentDate: "",
    enrollmentClass: "",
    branch: "",
    class2: "",
    height: "",
    width: "",
    footSize: "",
    uniformSize: "",
    weight: "",
    staffChildren: false,
  },
});

export const LANGUAGES = [
  "العربية",
  "التركية",
  "الإنجليزية",
  "الكردية",
  "أخرى",
];
export const STATUS_LABELS = {
  immigrant: "مهاجر",
  displaced: "نازح",
  resident: "مقيم",
  inactive: "غير نشط",
};
export const GENDER_LABELS = { male: "ذكر", female: "أنثى" };
export const ORPHAN_OF_LABELS = {
  mother: "الأم",
  father: "الأب",
  both: "كلاهما",
};
export const REGISTRATION_PATHS = ["خاص", "القرية", "الايتام"];
export const ORPHAN_DOC_TYPES = [
  "شهادة وفاة",
  "دفتر عائلة",
  "وثيقة محكمة",
  "أخرى",
];
export const SEMESTER_LABELS = {
  first: "الفصل الأول",
  second: "الفصل الثاني",
  full_year: "السنة كاملة",
};
